Document: dnssnarf
Title: Debian dnssnarf Manual
Author: <insert document author here>
Abstract: This manual describes what dnssnarf is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dnssnarf/dnssnarf.sgml.gz

Format: postscript
Files: /usr/share/doc/dnssnarf/dnssnarf.ps.gz

Format: text
Files: /usr/share/doc/dnssnarf/dnssnarf.text.gz

Format: HTML
Index: /usr/share/doc/dnssnarf/html/index.html
Files: /usr/share/doc/dnssnarf/html/*.html


