.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DNSSNARF 1 "February 10, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dnssnarf \- a DNS statistics gatherer for use with any DNS daemon.
.SH SYNOPSIS
.B dnssnarf
[-f] [-i INTERFACE]
.SH DESCRIPTION
This manual page documents briefly describes the
.B dnssnarf
daemon.
.PP
The dnssnarf daemon should be started and stopped via its init.d script, which is automatically installed by the package.
Configuration options are specified in
.B /etc/default/dnssnarf.
By default upon starting, the daemon will immediately fork itself and run into the background.
.TP
.B -f
Runs DNSsnarf in the foreground.
.TP
.B -i INTERFACE
Run DNSsnarf on the specified interface, instead of the system default.
.PP
Use the 
.B dnssnarfclient
tool to retrieve the statistics that dnssnarf gathers.
.SH SEE ALSO
.BR dnssnarfclient (1).
.br
.SH AUTHOR
dnssnarf was written by Peter Geissler <peter.geissler@cyso.nl> and Nick Douma <nick.douma@cyso.nl>
.PP
This manual page was written by Nick Douma <nick.douma@cyso.nl> for Cyso Managed Hosting, all rights reserved.
